batch_size: 100
clip_duration_ms: 1490
eval_step_interval: 500
features:
- features_dir: /Volumes/MachineLearning/training_data/alexa_4990ms_spectrogram/generated_positive
  penalty_weight: 1
  sampling_weight: 0.25
  truncation_strategy: truncate_start
  truth: true
- features_dir: /Volumes/MachineLearning/training_data/alexa_4990ms_spectrogram/generated_negative
  penalty_weight: 1
  sampling_weight: 0.25
  truncation_strategy: truncate_start
  truth: false
- features_dir: /Volumes/MachineLearning/training_data/english_speech_background_1970ms
  penalty_weight: 3
  sampling_weight: 0.2
  truncation_strategy: random
  truth: false
- features_dir: /Volumes/MachineLearning/training_data/cv_corpus_background
  penalty_weight: 2
  sampling_weight: 0.1
  truncation_strategy: random
  truth: false
- features_dir: /Volumes/MachineLearning/training_data/no_speech_background_1970ms
  penalty_weight: 3
  sampling_weight: 0.2
  truncation_strategy: random
  truth: false
- features_dir: /Volumes/MachineLearning/training_data/ambient_background
  penalty_weight: 2
  sampling_weight: 0.2
  truncation_strategy: split
  truth: false
freq_mask_count:
- 2
freq_mask_max_size:
- 5
freq_mix_augmentation_prob:
- 0
learning_rates:
- 0.001
- 0.0005
- 0.00025
maximization_metric: accuracy
minimization_metric: ambient_false_positives_per_hour
mix_up_augmentation_prob:
- 0
negative_class_weight:
- 1
positive_class_weight:
- 1
sample_rate: 16000
target_minimization: 0.5
time_mask_count:
- 2
time_mask_max_size:
- 5
train_dir: trained_models/dilation_test2
training_steps:
- 500
window_size_ms: 30
window_stride_ms: 20
