batch_size: 128
binary_classification: false
clip_duration_ms: 210
eval_step_interval: 500
features:
- features_dir: /Volumes/MachineLearning/training_data/alexa/positive_min_end_jitter
  penalty_weight: 1
  sampling_weight: 0.0
  truncation_strategy: truncate_start
  truth: true
  type: mmap
- augmentation_probabilities:
    AddBackgroundNoise: 0.75
    AddColorNoise: 0.25
    BandStopFilter: 0.1
    Gain: 1.0
    PitchShift: 0.1
    RIR: 0.5
    SevenBandParametricEQ: 0.1
    TanhDistortion: 0.1
  augmented_duration_s: 2.99
  background_paths:
  - /Volumes/MachineLearning/audio_samples/background_noise_samples/background_clips_for_mixing
  features_dir: /Users/kahrendt/Documents/Hobbies/Programming/Git-Repositories/piper-sample-generator/output/alexa
  impulse_paths:
  - /Volumes/MachineLearning/audio_samples/background_noise_samples/wav_16k/bird_rir_all_channels_16k
  input_glob: '*2/*.wav'
  max_clip_duration_s: 1.37
  max_jitter_s: 0.2
  max_start_time_from_right_s: null
  min_clip_duration_s: null
  min_jitter_s: 0.05
  penalty_weight: 1
  sampling_weight: 0.5
  truncation_strategy: truncate_start
  truth: true
  type: clips
- features_dir: /Volumes/MachineLearning/training_data/alexa/old_negative
  penalty_weight: 0.5
  sampling_weight: 0.5
  truncation_strategy: truncate_start
  truth: false
  type: mmap
- features_dir: /Volumes/MachineLearning/training_data/negative_datasets/speech_background_new
  penalty_weight: 1
  sampling_weight: 4
  truncation_strategy: random
  truth: false
  type: mmap
- features_dir: /Volumes/MachineLearning/training_data/negative_datasets/dinner_party_background_new
  penalty_weight: 1
  sampling_weight: 3
  truncation_strategy: random
  truth: false
  type: mmap
- features_dir: /Volumes/MachineLearning/training_data/negative_datasets/no_speech_background_new
  penalty_weight: 1
  sampling_weight: 3
  truncation_strategy: random
  truth: false
  type: mmap
- features_dir: /Volumes/MachineLearning/training_data/negative_datasets/ambient_background
  penalty_weight: 1
  sampling_weight: 0.0
  truncation_strategy: split
  truth: false
  type: mmap
freq_mask_count:
- 2
freq_mask_max_size:
- 4
freq_mix_augmentation_prob:
- 0
learning_rates:
- 0.001
- 0.0005
- 0.0002
maximization_metric: recall_at_no_faph
minimization_metric: null
mix_up_augmentation_prob:
- 0
negative_class_weight:
- 1
- 3
- 5
positive_class_weight:
- 1
target_minimization: 1.0
time_mask_count:
- 0
time_mask_max_size:
- 10
train_dir: trained_models/changes_revert_test
training_steps:
- 500
